version: '3.8'
services:
  app:
    build:
        context: ./../app_server
        target: development
    ports:
      - "3000:4000"
    depends_on:
      - db
      - minio

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: poep123
      MYSQL_DATABASE: poep_database
      MYSQL_BIND_ADDRESS: 0.0.0.0
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "127.0.0.1:33161:3306"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    build:
        context:  ./../minio
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data: